# Generated by Django 2.1.7 on 2019-03-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerokuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=10)),
                ('withdrawl', models.PositiveIntegerField(default=0)),
                ('total_money', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
